name: Deploy HTML Site

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM
        run: | 
          cd /var/www/html
          git clone https://github.com/mhabub/devops-learning.git