name: Deploy HTML Site

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read file contents
        id: read_file
        uses: actions/checkout@v1
        with:
          path: "hello.txt"

      - name: File contents
        run: echo "${{ steps.read_file.outputs.contents }}"
   
      - name: Deploy to VM
        run: | 
          cd /var/www/html/devops-learning
          git pull origin develop